using System;
using System.IO;
using UnityEditor;
using UnityEngine;

namespace ilodev.stationeersmods.tools.assetsfactory
{
    public static class FileUtils
    {
        /// <summary>
        /// Creates a file if it does not exist, ensuring the folder tree exists and refreshing the AssetDatabase.
        /// </summary>
        public static void CreateTextFile(string path, string content, bool overwrite = false)
        {
            string folder = Path.GetDirectoryName(path);
            EnsureFolders(folder);

            if (File.Exists(path) && !overwrite)
            {
                return;
            }

            File.WriteAllText(path, content);
            AssetDatabase.ImportAsset(path, ImportAssetOptions.ForceUpdate);
            AssetDatabase.Refresh();
        }

        /// <summary>
        /// Creates a folder tree if it does not exist.
        /// </summary>
        public static void EnsureFolders(string path)
        {
            if (!string.IsNullOrEmpty(path) && !Directory.Exists(path))
            {
                Directory.CreateDirectory(path);
            }
        }

        /// <summary>
        /// Generates a tiny component class that derives from a Stationeers base component.
        /// The generated file should remain behavior-free; create a separate subclass for custom logic.
        /// </summary>
        public static string GenerateScript(
            string className,
            string baseClassName,
            string addComponentMenuPath,
            string namespaceName)
        {
            string content = $@"using UnityEngine;

namespace {namespaceName}
{{
    [AddComponentMenu(""{addComponentMenuPath}"")]
    public class {className} : {baseClassName}
    {{
    // DO NOT EDIT THIS FILE. CREATE A NEW CLASS IF YOU NEED CUSTOM LOGIC ATTACHED TO YOUR ASSET.
    }}
}}
";

            return NormalizeLineEndings(content);
        }

        private static string NormalizeLineEndings(string text)
        {
            return text
                .Replace("\r\n", "\n")
                .Replace("\r", "\n")
                .Replace("\n", Environment.NewLine);
        }
    }
}
